DROP TABLE IF EXISTS activity_events CASCADE;
DROP TABLE IF EXISTS attachments CASCADE;
DROP TABLE IF EXISTS balance_projections CASCADE;
DROP TABLE IF EXISTS event_allocations CASCADE;
DROP TABLE IF EXISTS ledger_postings CASCADE;
DROP TABLE IF EXISTS financial_events CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS expense_payers CASCADE;
DROP TABLE IF EXISTS expense_splits CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS personal_transactions CASCADE;
DROP TABLE IF EXISTS personal_ledgers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS group_profiles CASCADE;
DROP TABLE IF EXISTS ledger_members CASCADE;
DROP TABLE IF EXISTS ledgers CASCADE;
DROP TABLE IF EXISTS connection_requests CASCADE;
DROP TABLE IF EXISTS user_blocks CASCADE;
DROP TABLE IF EXISTS idempotency_keys CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS refresh_sessions CASCADE;
DROP TABLE IF EXISTS device_tokens CASCADE;
DROP TABLE IF EXISTS notification_preferences CASCADE;
DROP TABLE IF EXISTS user_preferences CASCADE;
DROP TABLE IF EXISTS user_identities CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS reject_append_only_mutation();
DROP FUNCTION IF EXISTS enforce_financial_event();
DROP FUNCTION IF EXISTS assert_financial_event(uuid);
DROP FUNCTION IF EXISTS enforce_expense_allocations();
DROP FUNCTION IF EXISTS assert_expense_allocations(uuid);
DROP FUNCTION IF EXISTS enforce_ledger_shape();
DROP FUNCTION IF EXISTS assert_ledger_shape(uuid);

DROP TYPE IF EXISTS device_platform;
DROP TYPE IF EXISTS idempotency_status;
DROP TYPE IF EXISTS personal_report_mode;
DROP TYPE IF EXISTS category_kind;
DROP TYPE IF EXISTS personal_transaction_status;
DROP TYPE IF EXISTS personal_transaction_type;
DROP TYPE IF EXISTS event_allocation_role;
DROP TYPE IF EXISTS financial_event_type;
DROP TYPE IF EXISTS payment_status;
DROP TYPE IF EXISTS split_method;
DROP TYPE IF EXISTS expense_status;
DROP TYPE IF EXISTS ledger_member_status;
DROP TYPE IF EXISTS ledger_member_role;
DROP TYPE IF EXISTS ledger_status;
DROP TYPE IF EXISTS ledger_type;
DROP TYPE IF EXISTS connection_request_status;
DROP TYPE IF EXISTS identity_provider;
DROP TYPE IF EXISTS user_status;

DROP EXTENSION IF EXISTS citext;
